package decision

import ("crypto/sha256";"encoding/hex";"fmt";"strings")

const jevExternalApplyCapabilityReviewRevisionCandidateGenerationRequestCandidateGateRevisionProposalCandidateMaterializationLSPProjectionBound = "candidate-gate-revision-proposal-materialization-lsp-bound"

type JEVExternalApplyCapabilityReviewRevisionCandidateGenerationRequestCandidateGateRevisionProposalCandidateMaterializationLSPDiagnostic struct {
    Severity string; Code string; Message string; Status string; MissingStage string
    GenerationRequestStatus string; GenerationRequestDigest string; GenerationRequestSource string; GenerationRequestEvidenceDigest string; GeneratorIdentity string; ProposalDecision string; GenerationRequestCandidateGateRevisionProposalBridgeDigest string
    ApplicationPlanStatus string; ObservationMetricStatus string; ObservationMetricDigest string; ObservationMetricSource string; ObservationMetricEvidenceDigest string; ObservationStatus string; ObservationMetricDirectionDigest string
    CandidateGateStatus string; CandidateDecision string; CandidateDigest string; RevisionSource string; GateDigest string; FeedbackRevisionProposalStatus string; FeedbackStatus string; FeedbackBridgeDigest string
    RevisionProposalStatus string; RevisionProposalDecision string; RevisionProposalTarget string; RevisionProposalDigest string; RevisionProposalSource string; RevisionProposalEvidenceDigest string; FeedbackRevisionProposalBridgeDigest string
    MaterializationStatus string; GeneratedCandidateDigest string; GeneratedCandidateSource string; GenerationInputDigest string; GenerationEvidenceDigest string; CandidateGeneratorIdentity string; CandidateMaterializationBridgeDigest string; BridgeDigest string; ProjectionDigest string
    Publishable bool; NonExecuting bool; NonAuthorizing bool
}

func (d JEVExternalApplyCapabilityReviewRevisionCandidateGenerationRequestCandidateGateRevisionProposalCandidateMaterializationLSPDiagnostic) Validate() error {
    if d.Severity=="" || d.Code=="" || d.Message=="" || d.Status=="" { return fmt.Errorf("incomplete JEV candidate materialization LSP diagnostic") }
    if !d.NonExecuting || !d.NonAuthorizing { return fmt.Errorf("JEV candidate materialization LSP diagnostic must be non-executing and non-authorizing") }
    if d.Status==jevExternalApplyCapabilityReviewRevisionCandidateMaterializationAdmissionEvaluationBridgeUnknown { if d.Publishable || d.MissingStage=="" || d.BridgeDigest!="" || d.ProjectionDigest!="" { return fmt.Errorf("unknown JEV candidate materialization diagnostic must remain non-publishable") }; return nil }
    if d.Status!=jevExternalApplyCapabilityReviewRevisionCandidateGenerationRequestCandidateGateRevisionProposalCandidateMaterializationBridgeBound || !d.Publishable || d.MissingStage!="" || d.GenerationRequestCandidateGateRevisionProposalBridgeDigest=="" || d.CandidateMaterializationBridgeDigest=="" || d.GenerationRequestStatus=="" || d.GenerationRequestDigest=="" || d.GenerationRequestSource=="" || d.GenerationRequestEvidenceDigest=="" || d.GeneratorIdentity=="" || d.ProposalDecision=="" || d.ApplicationPlanStatus=="" || d.ObservationMetricStatus=="" || d.ObservationStatus=="" || d.ObservationMetricDirectionDigest=="" || d.CandidateGateStatus=="" || d.CandidateDecision=="" || d.GateDigest=="" || d.FeedbackRevisionProposalStatus=="" || d.FeedbackStatus=="" || d.FeedbackBridgeDigest=="" || d.RevisionProposalStatus=="" || d.MaterializationStatus=="" || d.BridgeDigest=="" || d.ProjectionDigest=="" { return fmt.Errorf("bound JEV candidate materialization diagnostic is incomplete") }
    switch d.CandidateDecision {
    case jevExternalApplyCapabilityReviewRevisionCandidateReady:
        if d.MaterializationStatus!=jevExternalApplyCapabilityReviewRevisionCandidateCapabilityScopeFeedbackRevisionProposalCandidateMaterialized || d.GeneratedCandidateDigest=="" || d.GeneratedCandidateSource=="" || d.GenerationInputDigest=="" || d.GenerationEvidenceDigest=="" || d.CandidateGeneratorIdentity=="" || d.RevisionProposalDecision!=jevExternalApplyCapabilityReviewRevisionCandidateCapabilityScopeFeedbackRevisionProposalRevise { return fmt.Errorf("materialized candidate diagnostic is incomplete") }
    case jevExternalApplyCapabilityReviewRevisionCandidateHold:
        if d.MaterializationStatus!=jevExternalApplyCapabilityReviewRevisionCandidateCapabilityScopeFeedbackRevisionProposalCandidateHeld || d.GeneratedCandidateDigest!="" || d.GeneratedCandidateSource!="" || d.GenerationInputDigest!="" || d.GenerationEvidenceDigest!="" || d.CandidateGeneratorIdentity!="" { return fmt.Errorf("held candidate diagnostic is inconsistent") }
    case jevExternalApplyCapabilityReviewRevisionCandidateRejected:
        if d.MaterializationStatus!=jevExternalApplyCapabilityReviewRevisionCandidateCapabilityScopeFeedbackRevisionProposalCandidateRollback || d.GeneratedCandidateDigest!="" || d.GeneratedCandidateSource!="" || d.GenerationInputDigest!="" || d.GenerationEvidenceDigest!="" || d.CandidateGeneratorIdentity!="" { return fmt.Errorf("rollback candidate diagnostic is inconsistent") }
    default: return fmt.Errorf("invalid candidate decision in LSP diagnostic")
    }
    expected:=digestJEVExternalApplyCapabilityReviewRevisionCandidateGenerationRequestCandidateGateRevisionProposalCandidateMaterializationLSPProjection(d.Status,d.GenerationRequestCandidateGateRevisionProposalBridgeDigest,d.FeedbackRevisionProposalBridgeDigest,d.CandidateMaterializationBridgeDigest,d.BridgeDigest,d.CandidateDecision,d.MaterializationStatus)
    if d.ProjectionDigest!=expected { return fmt.Errorf("JEV candidate materialization projection digest mismatch") }
    return nil
}

func ProjectJEVExternalApplyCapabilityReviewRevisionCandidateGenerationRequestCandidateGateRevisionProposalCandidateMaterializationLSP(input JEVExternalApplyCapabilityReviewRevisionCandidateGenerationRequestCandidateGateRevisionProposalCandidateMaterializationBridge) JEVExternalApplyCapabilityReviewRevisionCandidateGenerationRequestCandidateGateRevisionProposalCandidateMaterializationLSPDiagnostic {
    unknown:=func(stage string) JEVExternalApplyCapabilityReviewRevisionCandidateGenerationRequestCandidateGateRevisionProposalCandidateMaterializationLSPDiagnostic { if stage=="" { stage="candidate-gate-revision-proposal-materialization-lsp" }; return JEVExternalApplyCapabilityReviewRevisionCandidateGenerationRequestCandidateGateRevisionProposalCandidateMaterializationLSPDiagnostic{Severity:"warning",Code:"jev.provenance.unknown",Message:"Candidate materialization is UNKNOWN; evidence must be resolved",Status:jevExternalApplyCapabilityReviewRevisionCandidateMaterializationAdmissionEvaluationBridgeUnknown,MissingStage:stage,NonExecuting:true,NonAuthorizing:true} }
    if input.Status==jevExternalApplyCapabilityReviewRevisionCandidateMaterializationAdmissionEvaluationBridgeUnknown { return unknown(input.MissingStage) }
    if err:=input.Validate(); err!=nil { return unknown("candidate-materialization") }
    output:=JEVExternalApplyCapabilityReviewRevisionCandidateGenerationRequestCandidateGateRevisionProposalCandidateMaterializationLSPDiagnostic{Status:input.Status,GenerationRequestStatus:input.GenerationRequestStatus,GenerationRequestDigest:input.GenerationRequestDigest,GenerationRequestSource:input.GenerationRequestSource,GenerationRequestEvidenceDigest:input.GenerationRequestEvidenceDigest,GeneratorIdentity:input.GeneratorIdentity,ProposalDecision:input.ProposalDecision,GenerationRequestCandidateGateRevisionProposalBridgeDigest:input.GenerationRequestCandidateGateRevisionProposalBridgeDigest,ApplicationPlanStatus:input.ApplicationPlanStatus,ObservationMetricStatus:input.ObservationMetricStatus,ObservationMetricDigest:input.ObservationMetricDigest,ObservationMetricSource:input.ObservationMetricSource,ObservationMetricEvidenceDigest:input.ObservationMetricEvidenceDigest,ObservationStatus:input.ObservationStatus,ObservationMetricDirectionDigest:input.ObservationMetricDirectionDigest,CandidateGateStatus:input.CandidateGateStatus,CandidateDecision:input.CandidateDecision,CandidateDigest:input.CandidateDigest,RevisionSource:input.RevisionSource,GateDigest:input.GateDigest,FeedbackRevisionProposalStatus:input.FeedbackRevisionProposalStatus,FeedbackStatus:input.FeedbackStatus,FeedbackBridgeDigest:input.FeedbackBridgeDigest,RevisionProposalStatus:input.RevisionProposalStatus,RevisionProposalDecision:input.RevisionProposalDecision,RevisionProposalTarget:input.RevisionProposalTarget,RevisionProposalDigest:input.RevisionProposalDigest,RevisionProposalSource:input.RevisionProposalSource,RevisionProposalEvidenceDigest:input.RevisionProposalEvidenceDigest,FeedbackRevisionProposalBridgeDigest:input.FeedbackRevisionProposalBridgeDigest,MaterializationStatus:input.MaterializationStatus,GeneratedCandidateDigest:input.GeneratedCandidateDigest,GeneratedCandidateSource:input.GeneratedCandidateSource,GenerationInputDigest:input.GenerationInputDigest,GenerationEvidenceDigest:input.GenerationEvidenceDigest,CandidateGeneratorIdentity:input.CandidateGeneratorIdentity,CandidateMaterializationBridgeDigest:input.CandidateMaterializationBridgeDigest,BridgeDigest:input.BridgeDigest,Publishable:true,NonExecuting:true,NonAuthorizing:true,Severity:"info",Code:"jev.external-apply.candidate-materialization-bound",Message:"Candidate materialization provenance is bound without execution or authorization"}
    if input.CandidateDecision==jevExternalApplyCapabilityReviewRevisionCandidateHold { output.Code="jev.external-apply.candidate-materialization-held"; output.Message="Candidate materialization is held without execution or authorization" }
    if input.CandidateDecision==jevExternalApplyCapabilityReviewRevisionCandidateRejected { output.Severity="warning"; output.Code="jev.external-apply.candidate-materialization-rollback"; output.Message="Candidate materialization is rollback-only without execution or authorization" }
    output.ProjectionDigest=digestJEVExternalApplyCapabilityReviewRevisionCandidateGenerationRequestCandidateGateRevisionProposalCandidateMaterializationLSPProjection(output.Status,output.GenerationRequestCandidateGateRevisionProposalBridgeDigest,output.FeedbackRevisionProposalBridgeDigest,output.CandidateMaterializationBridgeDigest,output.BridgeDigest,output.CandidateDecision,output.MaterializationStatus)
    if err:=output.Validate(); err!=nil { return unknown("candidate-materialization-lsp") }
    return output
}

func digestJEVExternalApplyCapabilityReviewRevisionCandidateGenerationRequestCandidateGateRevisionProposalCandidateMaterializationLSPProjection(status,generationRequestCandidateGateRevisionProposalBridgeDigest,feedbackRevisionProposalBridgeDigest,candidateMaterializationBridgeDigest,bridgeDigest,candidateDecision,materializationStatus string) string { sum:=sha256.Sum256([]byte(strings.Join([]string{status,generationRequestCandidateGateRevisionProposalBridgeDigest,feedbackRevisionProposalBridgeDigest,candidateMaterializationBridgeDigest,bridgeDigest,candidateDecision,materializationStatus},"|"))); return hex.EncodeToString(sum[:]) }
